name: Build and Deploy to Docker Hub

on: 
  push: 
    branches: [main]

  pull_request:
    branches: [main]
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v3
          with: 
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASS}}
    
        - name: build image
          run: docker build --tag saphalpantha/serve-node:latest -f Dockerfile.dev .

        - name: push image to docker Hub
          run: |
            docker push saphalpantha/serve-node:latest
            
